name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v4
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v3.6.0
      with: 
        platforms: "riscv32"
    # - name: make
      # run: make
    - name: test
      run: ./run.sh
